# roles/nginx/tasks/main.yml
- name: Apt via https
  apt: name=apt-transport-https state=present
- name: Install nginx
  apt: pkg=nginx state=installed
- name: remove default nginx default
  file: path=/etc/nginx/sites-enabled/default state=absent
